/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Session as PrismaSession,
  OrderItem as PrismaOrderItem,
  Order as PrismaOrder,
  QueuePosition as PrismaQueuePosition,
  Ticket as PrismaTicket,
  Event as PrismaEvent,
} from "@prisma/client";

export class SessionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SessionCountArgs, "select">): Promise<number> {
    return this.prisma.session.count(args);
  }

  async sessions<T extends Prisma.SessionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SessionFindManyArgs>
  ): Promise<PrismaSession[]> {
    return this.prisma.session.findMany<Prisma.SessionFindManyArgs>(args);
  }
  async session<T extends Prisma.SessionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SessionFindUniqueArgs>
  ): Promise<PrismaSession | null> {
    return this.prisma.session.findUnique(args);
  }
  async createSession<T extends Prisma.SessionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SessionCreateArgs>
  ): Promise<PrismaSession> {
    return this.prisma.session.create<T>(args);
  }
  async updateSession<T extends Prisma.SessionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SessionUpdateArgs>
  ): Promise<PrismaSession> {
    return this.prisma.session.update<T>(args);
  }
  async deleteSession<T extends Prisma.SessionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.SessionDeleteArgs>
  ): Promise<PrismaSession> {
    return this.prisma.session.delete(args);
  }

  async findOrderItems(
    parentId: string,
    args: Prisma.OrderItemFindManyArgs
  ): Promise<PrismaOrderItem[]> {
    return this.prisma.session
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .orderItems(args);
  }

  async findOrders(
    parentId: string,
    args: Prisma.OrderFindManyArgs
  ): Promise<PrismaOrder[]> {
    return this.prisma.session
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .orders(args);
  }

  async findQueuePositions(
    parentId: string,
    args: Prisma.QueuePositionFindManyArgs
  ): Promise<PrismaQueuePosition[]> {
    return this.prisma.session
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .queuePositions(args);
  }

  async findTickets(
    parentId: string,
    args: Prisma.TicketFindManyArgs
  ): Promise<PrismaTicket[]> {
    return this.prisma.session
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .tickets(args);
  }

  async getEvents(parentId: string): Promise<PrismaEvent | null> {
    return this.prisma.session
      .findUnique({
        where: { id: parentId },
      })
      .events();
  }
}
