import { AddressListRelationFilter } from "../address/AddressListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { AttachmentListRelationFilter } from "../attachment/AttachmentListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { ContactAuthorizationWhereUniqueInput } from "../contactAuthorization/ContactAuthorizationWhereUniqueInput";
import { ContactListRelationFilter } from "../contact/ContactListRelationFilter";
import { DocumentListRelationFilter } from "../document/DocumentListRelationFilter";
import { EditedFieldListRelationFilter } from "../editedField/EditedFieldListRelationFilter";
import { FilialListRelationFilter } from "../filial/FilialListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { PhoneListRelationFilter } from "../phone/PhoneListRelationFilter";
import { RequestWhereUniqueInput } from "../request/RequestWhereUniqueInput";
import { SocioeconomicInfoListRelationFilter } from "../socioeconomicInfo/SocioeconomicInfoListRelationFilter";

export type HolderWhereInput = {
  addresses?: AddressListRelationFilter;
  affectionateFirstName?: StringNullableFilter;
  affectionateGender?: StringNullableFilter;
  affectionateLastName?: StringNullableFilter;
  attachments?: AttachmentListRelationFilter;
  birthDate?: DateTimeNullableFilter;
  contactAuthorization?: ContactAuthorizationWhereUniqueInput;
  contacts?: ContactListRelationFilter;
  documents?: DocumentListRelationFilter;
  editedFields?: EditedFieldListRelationFilter;
  education?: StringNullableFilter;
  filial?: FilialListRelationFilter;
  firstName?: StringNullableFilter;
  gender?: StringNullableFilter;
  id?: StringFilter;
  lastName?: StringNullableFilter;
  maritalStatus?: StringNullableFilter;
  phones?: PhoneListRelationFilter;
  request?: RequestWhereUniqueInput;
  socialFirstName?: StringNullableFilter;
  socialGender?: StringNullableFilter;
  socialLastName?: StringNullableFilter;
  socioeconomicInfo?: SocioeconomicInfoListRelationFilter;
  token?: StringNullableFilter;
  typeField?: StringNullableFilter;
};
