import { InputJsonValue } from "../../types";

export type HolderCreateInput = {
  addresses?: InputJsonValue;
  affectionateFirstName?: string | null;
  affectionateGender?: string | null;
  affectionateLastName?: string | null;
  attachments?: InputJsonValue;
  birthDate?: Date | null;
  contactAuthorizationId?: string | null;
  contacts?: InputJsonValue;
  documents?: InputJsonValue;
  editedFields?: InputJsonValue;
  education?: string | null;
  filial?: InputJsonValue;
  firstName?: string | null;
  gender?: string | null;
  lastName?: string | null;
  maritalStatus?: string | null;
  password: string;
  phones?: InputJsonValue;
  requestId: string;
  socialFirstName?: string | null;
  socialGender?: string | null;
  socialLastName?: string | null;
  socioeconomicInfo?: InputJsonValue;
  token?: string | null;
  typeField?: string | null;
  username: string;
};
