import { JsonFilter } from "../../util/JsonFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type HolderWhereInput = {
  addresses?: JsonFilter;
  affectionateFirstName?: StringNullableFilter;
  affectionateGender?: StringNullableFilter;
  affectionateLastName?: StringNullableFilter;
  attachments?: JsonFilter;
  birthDate?: DateTimeNullableFilter;
  contactAuthorizationId?: StringNullableFilter;
  contacts?: JsonFilter;
  documents?: JsonFilter;
  editedFields?: JsonFilter;
  education?: StringNullableFilter;
  filial?: JsonFilter;
  firstName?: StringNullableFilter;
  gender?: StringNullableFilter;
  id?: StringFilter;
  lastName?: StringNullableFilter;
  maritalStatus?: StringNullableFilter;
  password?: StringFilter;
  phones?: JsonFilter;
  requestId?: StringFilter;
  socialFirstName?: StringNullableFilter;
  socialGender?: StringNullableFilter;
  socialLastName?: StringNullableFilter;
  socioeconomicInfo?: JsonFilter;
  token?: StringNullableFilter;
  typeField?: StringNullableFilter;
  username?: StringFilter;
};
