import { JsonValue } from "type-fest";

export type Holder = {
  addresses: JsonValue;
  affectionateFirstName: string | null;
  affectionateGender: string | null;
  affectionateLastName: string | null;
  attachments: JsonValue;
  birthDate: Date | null;
  contactAuthorizationId: string | null;
  contacts: JsonValue;
  documents: JsonValue;
  editedFields: JsonValue;
  education: string | null;
  filial: JsonValue;
  firstName: string | null;
  gender: string | null;
  id: string;
  lastName: string | null;
  maritalStatus: string | null;
  password: string;
  phones: JsonValue;
  requestId: string;
  socialFirstName: string | null;
  socialGender: string | null;
  socialLastName: string | null;
  socioeconomicInfo: JsonValue;
  token: string | null;
  typeField: string | null;
  username: string;
};
