/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsBoolean,
} from "class-validator";
import { DependentCreateNestedManyWithoutRequestsInput } from "./DependentCreateNestedManyWithoutRequestsInput";
import { Type } from "class-transformer";
import { HolderCreateNestedManyWithoutRequestsInput } from "./HolderCreateNestedManyWithoutRequestsInput";
import { WorkerWhereUniqueInput } from "../../worker/base/WorkerWhereUniqueInput";

@InputType()
class RequestCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  channel?: string | null;

  @ApiProperty({
    required: false,
    type: () => DependentCreateNestedManyWithoutRequestsInput,
  })
  @ValidateNested()
  @Type(() => DependentCreateNestedManyWithoutRequestsInput)
  @IsOptional()
  @Field(() => DependentCreateNestedManyWithoutRequestsInput, {
    nullable: true,
  })
  dependents?: DependentCreateNestedManyWithoutRequestsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  finalize?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => HolderCreateNestedManyWithoutRequestsInput,
  })
  @ValidateNested()
  @Type(() => HolderCreateNestedManyWithoutRequestsInput)
  @IsOptional()
  @Field(() => HolderCreateNestedManyWithoutRequestsInput, {
    nullable: true,
  })
  holder?: HolderCreateNestedManyWithoutRequestsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ip?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  renewal?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  step?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeField?: string | null;

  @ApiProperty({
    required: true,
    type: () => WorkerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WorkerWhereUniqueInput)
  @Field(() => WorkerWhereUniqueInput)
  worker!: WorkerWhereUniqueInput;
}

export { RequestCreateInput as RequestCreateInput };
